#!/bin/bash

SCRIPT_PATH="$(realpath "$0")"
INSTALL_DIR=${INSTALL_DIR:-"$HOME/.local/bin/contain"}

SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
mkdir -p "$INSTALL_DIR"
rm -rf "${INSTALL_DIR}/*" || true
cp -r "${SCRIPT_DIR}"/{contain,proxy-socket,specs} "${INSTALL_DIR}"

# Add script dir to path, manage by ```# >>> contain initialize` and `# <<< contain initialize` markers
# 1. Remove everything between the markers if they exist (including the markers)
# 2. Add the markers and the new path to the script dir
sed -i '/# >>> contain initialize/,/# <<< contain initialize/d' ~/.bashrc
cat << EOF >> ~/.bashrc
# >>> contain initialize
export PATH="$SCRIPT_DIR/bin/contain:\$PATH"
# <<< contain initialize
EOF
