ARG BASE
FROM $BASE

RUN apt-get update && apt-get install -y wget gpg ca-certificates --no-install-recommends

RUN wget -4 -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/packages.microsoft.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" \
        > /etc/apt/sources.list.d/vscode.list

RUN apt-get update && apt-get install -y code --no-install-recommends

RUN apt-get install -y \
    bash git cmake build-essential curl unzip \
    gcc g++ \
    vim nano \
    libx11-dev libxkbfile-dev libsecret-1-dev \
    libsecret-1-0 \
    python3 python3-pip \
    nodejs npm \
    lldb \
    valgrind \
    gdb \
    strace \
    ltrace \
    net-tools \
    iputils-ping \
    procps \
    htop \
    tcpdump \
    netcat-openbsd \
    ffmpeg \
    libsdl2-2.0-0 \
    libusb-1.0-0 \
    socat

RUN apt-get install -y libsdl2-dev \
                 libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
                 libswresample-dev libusb-1.0-0-dev

RUN apt-get install -y --no-install-recommends \
    zip default-jdk \
    pkg-config meson ninja-build build-essential



RUN apt-get clean && rm -rf /var/lib/apt/lists/*
