ARG BASE
FROM $BASE

# Add Google's signing key and repository
RUN rpm --import https://dl.google.com/linux/linux_signing_key.pub && \
    echo -e "[google-chrome]\nname=Google Chrome\nbaseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64\nenabled=1\ngpgcheck=1\ngpgkey=https://dl.google.com/linux/linux_signing_key.pub" \
        > /etc/yum.repos.d/google-chrome.repo

RUN dnf install -y google-chrome-stable && dnf clean all

RUN dnf install -y librsvg2

WORKDIR /home/user
